[package]
name = "spider"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
reqwest = { version = "0.12.5", features = ["blocking"]}
scraper = "0.19.0"
url = "2.5.2"